[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://jacmportfolio.netlify.app"
  CONTENTFUL_SPACE_ID = "8lgocq2r7pfg"
  CONTENTFUL_ENVIRONMENT = "master"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  function = "contentful"
  path = "/*"
